### ISSUE TITLE
Javascript only needed for Admin should not load on view

### ISSUE THREAD

**Issue by wshafer** [reliv/Rcm#292]
Hey guys,

We're tracking down some issues with performance for our site.  We noticed that all the Admin JS gets loaded when no admin screens are present.

I noticed that all of these get shoved into the rcmHtmlIncludes() but really we should only be including things that are needed.

Obviously I can jump in here and fix this, but before I move on this I want to make sure I won't be breaking anything for you guys.

**Comment by rodmcnew** [comment]
We have alot of thoughts on how to better handle JS includes as well. We would like to eventually have the option to not use the asset manager.

I believe last time we discussed, we found that we need several different "lists" of JS files in the RCM config. Perhaps admin files could be one of these lists.

@jerv13  - James do you remember if what I am saying above is what we came to conclude last time?

**Comment by rodmcnew** [comment]
On the performance note, I recently did alot of profiling with CacheGrind. Surprisingly it was hard to find major slow areas where alot of improvement could be made. I found most of the time was taken by four things: ZF Router, ZF Service Manager, and Doctrine. Symfony generates a fast cache compiled version of their router and service manager but we do not have that option in ZF.

One thing we could do is get onto the ZF3 service manager. The only barrier to it that I see is that so many composer.jsons (including the aws tools) demand the 2.* service manager even though they would work the the 3.* one.

**Comment by wshafer** [comment]
There's something else too. Including all the files in one JS is now also considered bad practice and shouldn't be used anymore with http 2. 

I got dinged pretty hard on this by our optimization consultant.

I'm all for getting rid of the AssetManager so long as installing assets is easy and doesn't require node on the production boxes. If you have a better idea on this I'm all ears.

**Comment by wshafer** [comment]
Actually in performance we got A GLOWING review on the backend.  Where we got killed was on the front end.

**Comment by rodmcnew** [comment]
There are two separate things:
1) The FXP Composer-bower thing
2) The asset manager

Here is how we are getting rid of the asset manager (but keeping FXP now) in our current setup:
1) We configured the composer bower thing to install directly into the public folder.
2) Our front-end combined/minified JS files for each package are pre-built into dist folders inside those packages with grunt

If you do those, you only need node on you local and maybe your build servers, not on your prod servers.

Not everyone has to do things this way but this is how we are doing it now.

**Comment by rodmcnew** [comment]
"Actually in performance we got A GLOWING review on the backend. Where we got killed was on the front end." - This makes sense.

**Comment by rodmcnew** [comment]
That method of getting rid of the asset manager above only applies to front end apps and front end libraries though. Of course the asset manager is still currently needed to server public assets that are in cms plugin folders.

**Comment by rodmcnew** [comment]
Also one more note: We are not currently wanting to REMOVE the asset manager. We just want the option to not use it for front in apps and libraries.

**Comment by rodmcnew** [comment]
@wshafer Where are you seeing admin-js loading when not an admin? I do not see it here 

view-source:https://reliv.com/

**Comment by wshafer** [comment]
Angular, tinyMCE are being loaded every request.

**Comment by wshafer** [comment]
There's some other unneeded js libraries as well.

**Comment by wshafer** [comment]
As for the Asset Manager, yea I hit the same wall. How to plugins include their assets the easiest.  Requiring node seems a bit much for quick easy plugins. 

For full on apps, it makes complete sense to move those out to bower/npm, I just wish FXP wasn't so damn slow!

**Comment by rodmcnew** [comment]
I have alot of problems with FXP's slowness, bugs, breaking build, and the fact that it has to be global installed. But we cannot think of anything better right now.

**Comment by rodmcnew** [comment]
I personally think core should NOT include tinyMCE. Debating with @jerv13 right now.

**Comment by wshafer** [comment]
If I can put in my two cents.  Anything ONLY required for admin should not be loading.  Let the theme's + plugins add as needed.

In our world the only thing that uses Angular is the admin section (much to my dismay).  Our frontend team is using Redux and React for everything front end.  None of our plugins use this.

**Comment by rodmcnew** [comment]
Just got done with a long discussion with @jerv13 

@jerv13 is pretty adamant that Rcm should dictate/manage a certain version of jQuery and Angular in order to simplify development, compatibility, and JS loading order. In order to keep providing this but still allow @wshafer to do what he wants, we are going to do these today:
1) Make a new module rcm/js-core.
2) Move all front-end js and css inclusion from rcm/core to rcm/js-core

js-core will be used in the rcm skeleton app and will dictate jQuery and Angular versions (and TinyMce for now since it is used for cases other than admin)

@wshafer can disable js-core if he want to manage the js himself

**Comment by rodmcnew** [comment]
Supposable this helps with speeding up FXP. Idk how much it helped us though. Maybe we need a better regex. https://github.com/fxpio/composer-asset-plugin/issues/237

**Comment by wshafer** [comment]
Ok sounds good. What do I need to do to ensure all the Admin required JS is loaded for Admins?  Will these be included and injected via RCM-admin like they use to?

**Comment by wshafer** [comment]
My issue was not the version but the automatic inclusion when not logged in.

**Comment by wshafer** [comment]
Oh but this would fix the earlier issue with bootstrap. Nice.

**Comment by rodmcnew** [comment]
As far as I know, rcm-admin already injects the admin.js only when you are logged in.

For angular, tinymce, and other things that the admin.js depends on, you will need some way to include these selectively. Perhaps by injecting them into admin.js?

We do not include these selectively because all our pages use angular and many use TinyMce. Also because @jerv13 wants to keep JS dependency management simple for now by just including all the commonly used dependencies on every page.

**Comment by rodmcnew** [comment]
Also... by "Version" I also meant the @jerv13 wants Rcm to dictate that these libraries are included on every page so that plugins can depend on them being there. He said all three of us (including Westin) discussed this in detail and came to this decision.

Of course this will only happen in the future if the core-js module is enabled.

**Comment by wshafer** [comment]
What if we just simply include them like the other JS files and let Zend sort it all out.

Like the other JS libraries in:
cms/vendor/rcm/admin/view/rcm-admin/admin/admin.phtml

Simply adding them to this should fix all of this, since I can just overwrite the rcm list from my local.config.php.

**Comment by wshafer** [comment]
Ya know what... I can do that right now cant I.  Let me experiment.

**Comment by wshafer** [comment]
This gets me closer but not quite there.  Loading order is a problem here.
module.php
```
public function init(ModuleManager $moduleManager)
    {
        $events = $moduleManager->getEventManager();

        // Registering a listener at default priority, 1, which will trigger
        // after the ConfigListener merges config.
        $events->attach(ModuleEvent::EVENT_MERGE_CONFIG, array($this, 'onMergeConfig'));
    }

    public function onMergeConfig(ModuleEvent $e)
    {
        $configListener = $e->getConfigListener();
        $config         = $configListener->getMergedConfig(false);

        // Modify the configuration; here, we'll remove a specific key:
        $config['asset_manager']['resolver_configs']['collections']['modules/rcm-admin/admin.js'] = array_merge(
            $config['Rcm']['HtmlIncludes']['headScriptFile'],
            $config['asset_manager']['resolver_configs']['collections']['modules/rcm-admin/admin.js'],
            $config['asset_manager']['resolver_configs']['collections']['modules/rcm/rcm.js']
        );

        $config['asset_manager']['resolver_configs']['collections']['modules/rcm-admin/admin.js']
            = array_reverse($config['asset_manager']['resolver_configs']['collections']['modules/rcm-admin/admin.js']);

        $config['asset_manager']['resolver_configs']['collections']['modules/rcm-admin/admin.css'] = array_merge(
            $config['asset_manager']['resolver_configs']['collections']['modules/rcm/rcm.css'],
            $config['asset_manager']['resolver_configs']['collections']['modules/rcm-admin/admin.css']
        );

        $config['Rcm']['HtmlIncludes']['headScriptFile'] = [];
        $config['asset_manager']['resolver_configs']['collections']['modules/rcm/rcm.js'] = [];
        $config['asset_manager']['resolver_configs']['collections']['modules/rcm/rcm.css'] = [];

        // Pass the changed configuration back to the listener:
        $configListener->setMergedConfig($config);
    }
```

**Comment by wshafer** [comment]
lol...  ok I'm on to something... JUST DON'T INCLUDE $this->rcmHtmlIncludes(); in my theme!

So that absolutely worked AND is being injected by the admin.phtml template.

Course now I get to find out which plugins are REALLY using Angular.  A couple of them are.

**Comment by wshafer** [comment]
Thanks for your help guys.   I appreciate all the time you took out of your day.

Now it's on to ZF3

**Comment by rodmcnew** [comment]
Sounds good. We are still going to separate core-js from the core module.

**Comment by rodmcnew** [comment]
...everything in the core public folder will move to the core-js module
